INSERT INTO USER (ID,NAME) VALUES
(1,'admin');
INSERT INTO USER (ID,NAME) VALUES
(2,'user');
INSERT INTO USER (ID,NAME) VALUES
(3,'customer');
INSERT INTO USER (ID,NAME) VALUES
(4,'Lenchik Pirozhkov');
